name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/swj-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Write key
        env:
          AUTH: ${{ secrets.AUTH }}
        run: |
          echo "${{ secrets.CERTIFICATE_KEY }}" | base64 --decode > swj.key

      - name: Write certificate
        env:
          AUTH: ${{ secrets.AUTH }}
        run: |
          echo "${{ secrets.CERTIFICATE }}" | base64 --decode > swj.crt

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}