name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
  workflow_call: #Reusable for when the PR is merged
    secrets:
      DOCKER_HUB_PASSWORD:
        required: true
      DOCKER_HUB_USERNAME:
        required: true
      CERTIFICATE:
        required: true
      CERTIFICATE_KEY:
        required: true

env:
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  CERTIFICATE_KEY: ${{ secrets.CERTIFICATE_KEY }}
  CERTIFICATE: ${{ secrets.CERTIFICATE }}
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/swj-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Write key
        run: |
          echo "${{ env.CERTIFICATE_KEY }}" | base64 --decode > swj.key

      - name: Write certificate
        run: |
          echo "${{ env.CERTIFICATE }}" | base64 --decode > swj.crt

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}